version: "3"
services:
  #####################################
  # Reverse Proxy              #
  #####################################
  reverse:
    container_name: reverse
    image: ${REGISTRY}/docker-poc-reverse:${VERSION}
    logging:
      driver: ${LOG_DRIVER}
      options:
        max-file: ${LOG_MAX_FILES}
        max-size: ${LOG_MAX_SIZE}
    build:
      context: ./reverse
      dockerfile: prod.Dockerfile
    env_file:
      - ./reverse/.prod.env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    networks:
      - docker-registry-poc
  #####################################
  # App                               #
  #####################################
  webserver:
    container_name: webserver
    image: ${REGISTRY}/docker-poc-webserver:${VERSION}
    logging:
      driver: ${LOG_DRIVER}
      options:
        max-file: ${LOG_MAX_FILES}
        max-size: ${LOG_MAX_SIZE}
    build:
      context: ./webserver
      dockerfile: prod.Dockerfile
    env_file:
      - ./webserver/.prod.env
    networks:
      - docker-registry-poc
networks:
  docker-registry-poc:
    driver: "bridge"
